<div class="mb-6 flex flex-wrap justify-between gap-3 items-end">
  <div><h1 class="text-3xl font-heading font-semibold text-royal-900">Asset Management</h1><p class="text-mist-600 text-sm mt-1">Register, view, update and delete church assets.</p></div>
  <button id="asset-add-btn" class="px-4 py-2.5 rounded-xl bg-royal-600 text-white font-semibold text-sm">Add Asset</button>
</div>
<div id="asset-form-card" class="hidden bg-white border border-mist-200 rounded-2xl p-5 mb-5">
<div class="flex justify-between mb-3"><h2 id="asset-form-title" class="font-semibold">Add Asset</h2><button id="asset-close" type="button" class="text-sm text-mist-500">Close</button></div>
<form id="asset-form" class="grid md:grid-cols-3 gap-3"><input type="hidden" id="asset-id">
<input name="name" required placeholder="Asset name" class="rounded-xl border border-mist-200 px-3 py-2.5"><input name="category" required placeholder="Category" class="rounded-xl border border-mist-200 px-3 py-2.5"><input name="current_location" required placeholder="Current location" class="rounded-xl border border-mist-200 px-3 py-2.5">
<input name="purchase_date" type="date" class="rounded-xl border border-mist-200 px-3 py-2.5"><input name="purchase_value" type="number" min="0" step="0.01" placeholder="Purchase value" class="rounded-xl border border-mist-200 px-3 py-2.5"><select name="condition_status" class="rounded-xl border border-mist-200 px-3 py-2.5"><option>good</option><option>excellent</option><option>fair</option><option>poor</option><option>retired</option></select>
<textarea name="notes" placeholder="Notes" class="md:col-span-2 rounded-xl border border-mist-200 px-3 py-2.5"></textarea><button class="rounded-xl bg-royal-600 text-white font-semibold">Save Asset</button>
</form><div id="asset-feedback" class="text-sm mt-2"></div></div>
<div class="bg-white border border-mist-200 rounded-2xl p-5">
<div class="flex gap-2 mb-4"><input id="asset-search" placeholder="Search tag, name or location" class="flex-1 rounded-xl border border-mist-200 px-3 py-2.5"><select id="condition" class="rounded-xl border border-mist-200 px-3"><option value="">All conditions</option><option>excellent</option><option>good</option><option>fair</option><option>poor</option><option>retired</option></select></div>
<div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="text-left border-b"><th class="py-3">Tag</th><th>Name</th><th>Category</th><th>Location</th><th>Condition</th><th>Maintenance</th><th>Actions</th></tr></thead><tbody id="asset-rows"></tbody></table></div></div>
<script>
const AAPI=BASE_URL+'/api/v1'; let assetCache=[];
const ae=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function loadAssets(){const p=new URLSearchParams();const q=document.getElementById('asset-search').value.trim(),c=document.getElementById('condition').value;if(q)p.set('search',q);if(c)p.set('condition',c);const r=await fetch(AAPI+'/assets?'+p);const j=await r.json();assetCache=j.data||[];document.getElementById('asset-rows').innerHTML=assetCache.map(a=>`<tr class="border-b border-mist-100"><td class="py-3 font-semibold">${ae(a.asset_tag)}</td><td>${ae(a.name)}</td><td>${ae(a.category)}</td><td>${ae(a.current_location)}</td><td>${ae(a.condition_status)}</td><td>${ae(a.latest_maintenance_date||'—')}</td><td><div class="flex gap-2"><button onclick="viewAsset(${a.id})" class="text-xs font-semibold text-emerald-700">View</button><button onclick="editAsset(${a.id})" class="text-xs font-semibold text-royal-700">Update</button><button onclick="deleteAsset(${a.id})" class="text-xs font-semibold text-red-600">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="py-8 text-center text-mist-500">No assets found.</td></tr>'}
function viewAsset(id){const a=assetCache.find(x=>Number(x.id)===Number(id));if(a)alert(`${a.asset_tag}\n${a.name}\nCategory: ${a.category}\nLocation: ${a.current_location}\nCondition: ${a.condition_status}\nPurchase value: ${a.purchase_value||'—'}\nNotes: ${a.notes||'—'}`)}
function editAsset(id){const a=assetCache.find(x=>Number(x.id)===Number(id));if(!a)return;const f=document.getElementById('asset-form');document.getElementById('asset-id').value=id;document.getElementById('asset-form-title').textContent='Update Asset';['name','category','current_location','purchase_date','purchase_value','condition_status','notes'].forEach(n=>{if(f[n])f[n].value=a[n]??''});document.getElementById('asset-form-card').classList.remove('hidden');document.getElementById('asset-form-card').scrollIntoView({behavior:'smooth'});}
async function deleteAsset(id){if(!confirm('Delete this asset and its maintenance history?'))return;const r=await fetch(AAPI+'/assets/'+id,{method:'DELETE'});const j=await r.json();alert(j.message||'Done');if(j.success)loadAssets();}
document.getElementById('asset-add-btn').onclick=()=>{document.getElementById('asset-form').reset();document.getElementById('asset-id').value='';document.getElementById('asset-form-title').textContent='Add Asset';document.getElementById('asset-form-card').classList.remove('hidden')};document.getElementById('asset-close').onclick=()=>document.getElementById('asset-form-card').classList.add('hidden');document.getElementById('asset-search').addEventListener('input',loadAssets);document.getElementById('condition').addEventListener('change',loadAssets);
document.getElementById('asset-form').addEventListener('submit',async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const id=document.getElementById('asset-id').value;const r=await fetch(AAPI+'/assets'+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();document.getElementById('asset-feedback').textContent=j.message||'';if(j.success){e.target.reset();document.getElementById('asset-id').value='';document.getElementById('asset-form-card').classList.add('hidden');loadAssets();}});if(new URLSearchParams(location.search).get('action')==='create')document.getElementById('asset-add-btn').click();loadAssets();
</script>
