<div class="max-w-7xl mx-auto space-y-6">
  <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
    <div><h1 class="text-3xl font-heading font-semibold text-royal-900">Events / Ibada</h1><p class="text-mist-600 text-sm mt-1">Register every service or church event before recording attendance.</p></div>
    <button id="new-event-btn" class="px-4 py-2.5 rounded-xl bg-royal-600 text-white font-semibold">+ New Event / Ibada</button>
  </div>

  <section id="event-form-card" class="hidden bg-white border border-mist-200 rounded-2xl p-5 shadow-sm">
    <div class="flex items-center justify-between mb-4"><h2 id="event-form-title" class="font-semibold text-lg">Register Event / Ibada</h2><button type="button" id="cancel-event" class="text-sm text-mist-500 hover:text-royal-700">Close</button></div>
    <form id="event-form" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <input type="hidden" name="id" id="event-id">
      <label class="text-sm"><span class="font-medium">Event / Ibada Name *</span><input name="title" required class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5" placeholder="e.g. Sunday Worship"></label>
      <label class="text-sm"><span class="font-medium">Type *</span><select name="event_type" required class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"><option value="service">Service / Ibada</option><option value="seminar">Seminar</option><option value="meeting">Meeting</option><option value="appointment">Appointment</option><option value="other">Other</option></select></label>
      <label class="text-sm"><span class="font-medium">Date *</span><input name="date" type="date" required class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"></label>
      <label class="text-sm"><span class="font-medium">Start Time *</span><input name="time" type="time" required class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"></label>
      <label class="text-sm"><span class="font-medium">Duration (hours)</span><input name="duration_hours" type="number" min="0.5" step="0.5" value="2" class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"></label>
      <label class="text-sm"><span class="font-medium">Location *</span><input name="location" required class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5" placeholder="Main Auditorium"></label>
      <label class="text-sm"><span class="font-medium">Expected Attendance</span><input name="expected_attendance" type="number" min="0" class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"></label>
      <label class="text-sm"><span class="font-medium">Status</span><select name="status" class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"><option value="planned">Planned</option><option value="draft">Draft</option><option value="ongoing">Ongoing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>
      <label class="text-sm md:col-span-2 lg:col-span-3"><span class="font-medium">Description / Notes</span><textarea name="description" rows="2" class="mt-1 w-full rounded-xl border border-mist-200 px-3 py-2.5"></textarea></label>
      <div class="md:col-span-2 lg:col-span-3 flex items-center gap-3"><button class="px-5 py-2.5 rounded-xl bg-royal-600 text-white font-semibold">Save Event / Ibada</button><span id="event-feedback" class="text-sm"></span></div>
    </form>
  </section>

  <section class="bg-white border border-mist-200 rounded-2xl shadow-sm overflow-hidden">
    <div class="p-4 border-b border-mist-100 flex flex-col md:flex-row gap-3 md:items-center md:justify-between">
      <h2 class="font-semibold text-lg">Registered Events / Ibada</h2>
      <div class="flex gap-2"><input id="event-search" class="rounded-xl border border-mist-200 px-3 py-2 text-sm" placeholder="Search event..."><input id="event-month" type="month" class="rounded-xl border border-mist-200 px-3 py-2 text-sm"></div>
    </div>
    <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-mist-50"><tr class="text-left"><th class="p-3">Event</th><th class="p-3">Type</th><th class="p-3">Date & Time</th><th class="p-3">Location</th><th class="p-3">Status</th><th class="p-3">Actions</th></tr></thead><tbody id="event-rows"></tbody></table></div>
  </section>
</div>
<script>
const EAPI=BASE_URL+'/api/v1'; let eventsCache=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function openEventForm(row=null){const c=document.getElementById('event-form-card'),f=document.getElementById('event-form');c.classList.remove('hidden');f.reset();f.duration_hours.value=2;document.getElementById('event-id').value='';document.getElementById('event-form-title').textContent='Register Event / Ibada';if(row){document.getElementById('event-form-title').textContent='Update Event / Ibada';document.getElementById('event-id').value=row.id;f.title.value=row.title||'';f.event_type.value=row.event_type||'service';const d=new Date(String(row.start_datetime).replace(' ','T'));f.date.value=String(row.start_datetime).slice(0,10);f.time.value=String(row.start_datetime).slice(11,16);const end=new Date(String(row.end_datetime).replace(' ','T'));f.duration_hours.value=Math.max(.5,(end-d)/3600000)||2;f.location.value=row.location||'';f.expected_attendance.value=row.expected_attendance??'';f.status.value=row.status||'planned';f.description.value=row.description||'';}c.scrollIntoView({behavior:'smooth',block:'start'});}
async function loadEvents(){const month=document.getElementById('event-month').value;const r=await fetch(EAPI+'/events'+(month?'?month='+encodeURIComponent(month):''));const j=await r.json();eventsCache=j.data||[];renderEvents();}
function renderEvents(){const q=document.getElementById('event-search').value.toLowerCase();const list=eventsCache.filter(x=>!q||`${x.title} ${x.event_type} ${x.location}`.toLowerCase().includes(q));document.getElementById('event-rows').innerHTML=list.map(x=>`<tr class="border-t border-mist-100"><td class="p-3"><div class="font-semibold text-mist-900">${esc(x.title)}</div><div class="text-xs text-mist-500">${esc(x.event_code)}</div></td><td class="p-3 capitalize">${esc(x.event_type)}</td><td class="p-3">${esc(x.start_datetime)}</td><td class="p-3">${esc(x.location||'—')}</td><td class="p-3 capitalize">${esc(x.status)}</td><td class="p-3"><div class="flex gap-2"><button data-view="${x.id}" class="text-xs font-semibold text-emerald-700">View</button><button data-edit="${x.id}" class="text-xs font-semibold text-royal-700">Update</button><button data-del="${x.id}" class="text-xs font-semibold text-red-600">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="p-8 text-center text-mist-500">No events registered.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEventForm(eventsCache.find(x=>x.id==b.dataset.edit)));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const x=eventsCache.find(x=>x.id==b.dataset.view);alert(`${x.title}\n${x.start_datetime}\n${x.location||''}\nStatus: ${x.status}\n\n${x.description||'No description.'}`)});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this event / ibada?'))return;const r=await fetch(EAPI+'/events/'+b.dataset.del,{method:'DELETE'});const j=await r.json();alert(j.message||'Done');if(j.success)loadEvents();});}
document.getElementById('new-event-btn').onclick=()=>openEventForm();document.getElementById('cancel-event').onclick=()=>document.getElementById('event-form-card').classList.add('hidden');document.getElementById('event-search').oninput=renderEvents;document.getElementById('event-month').onchange=loadEvents;
document.getElementById('event-form').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const id=body.id;delete body.id;const r=await fetch(EAPI+'/events'+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();document.getElementById('event-feedback').textContent=j.message||'';document.getElementById('event-feedback').className='text-sm '+(j.success?'text-emerald-700':'text-red-600');if(j.success){document.getElementById('event-form-card').classList.add('hidden');loadEvents();}};
if(new URLSearchParams(location.search).get('action')==='create')openEventForm();loadEvents();
</script>
