<div class="mb-6"><h1 class="text-3xl font-heading font-semibold text-royal-900">Church Giving</h1><p class="text-mist-600 text-sm mt-1">Record, view, update and delete tithes, offerings, donations and other approved givings.</p></div>
<div class="grid lg:grid-cols-3 gap-5">
<section class="bg-white border border-mist-200 rounded-2xl p-5"><h2 id="giving-form-title" class="font-semibold text-lg mb-4">Record Giving</h2><form id="giving-form" class="space-y-3"><input type="hidden" id="giving-id"><input name="entry_date" type="date" required class="w-full rounded-xl border border-mist-200 px-3 py-2.5"><select id="giving-category" name="category_id" required class="w-full rounded-xl border border-mist-200 px-3 py-2.5"><option value="">Select category</option></select><input name="amount" type="number" min="1" step="0.01" required placeholder="Amount (TZS)" class="w-full rounded-xl border border-mist-200 px-3 py-2.5"><select name="payment_method" required class="w-full rounded-xl border border-mist-200 px-3 py-2.5"><option value="cash">Cash</option><option value="mobile_money">Mobile money</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select><input name="description" required placeholder="Description" class="w-full rounded-xl border border-mist-200 px-3 py-2.5"><button class="w-full rounded-xl bg-royal-600 text-white py-2.5 font-semibold">Save Giving</button><button type="button" id="giving-cancel" class="hidden w-full rounded-xl border border-mist-200 py-2.5 font-semibold">Cancel Update</button></form><div id="giving-feedback" class="mt-2 text-sm"></div></section>
<section class="lg:col-span-2 bg-white border border-mist-200 rounded-2xl p-5"><div class="flex justify-between mb-4"><h2 class="font-semibold text-lg">Giving Records</h2><strong id="giving-total">TZS 0</strong></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="text-left border-b"><th class="py-3">Date</th><th>Category</th><th>Method</th><th>Description</th><th class="text-right">Amount</th><th>Actions</th></tr></thead><tbody id="giving-rows"></tbody></table></div></section>
</div>
<script>
const FAPI=BASE_URL+'/api/v1';let givingRows=[];const ge=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function loadCats(){const r=await fetch(FAPI+'/finance/categories');const j=await r.json();document.getElementById('giving-category').innerHTML='<option value="">Select category</option>'+((j.data||[]).filter(c=>c.category_type==='income').map(c=>`<option value="${c.id}">${ge(c.name)}</option>`).join(''));}
async function loadGiving(){const r=await fetch(FAPI+'/finance/entries');const j=await r.json();givingRows=(j.data||[]).filter(x=>x.category_type==='income');document.getElementById('giving-rows').innerHTML=givingRows.map(x=>`<tr class="border-b border-mist-100"><td class="py-3">${x.entry_date}</td><td>${ge(x.category_name)}</td><td>${ge(x.payment_method)}</td><td>${ge(x.description||'')}</td><td class="text-right font-semibold">TZS ${Number(x.amount).toLocaleString()}</td><td><div class="flex gap-2 ml-3"><button onclick="viewGiving(${x.id})" class="text-xs font-semibold text-emerald-700">View</button><button onclick="editGiving(${x.id})" class="text-xs font-semibold text-royal-700">Update</button><button onclick="deleteGiving(${x.id})" class="text-xs font-semibold text-red-600">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="text-center py-8 text-mist-500">No giving records.</td></tr>';document.getElementById('giving-total').textContent='TZS '+givingRows.reduce((a,x)=>a+Number(x.amount||0),0).toLocaleString();}
function viewGiving(id){const x=givingRows.find(r=>Number(r.id)===Number(id));if(x)alert(`${x.entry_date}\n${x.category_name}\n${x.payment_method}\nTZS ${Number(x.amount).toLocaleString()}\n${x.description||''}`)}
function editGiving(id){const x=givingRows.find(r=>Number(r.id)===Number(id));if(!x)return;const f=document.getElementById('giving-form');document.getElementById('giving-id').value=id;document.getElementById('giving-form-title').textContent='Update Giving';f.entry_date.value=x.entry_date;f.category_id.value=x.category_id||'';f.amount.value=x.amount;f.payment_method.value=x.payment_method;f.description.value=x.description||'';document.getElementById('giving-cancel').classList.remove('hidden');f.scrollIntoView({behavior:'smooth'});}
function resetGiving(){const f=document.getElementById('giving-form');f.reset();document.getElementById('giving-id').value='';document.getElementById('giving-form-title').textContent='Record Giving';document.getElementById('giving-cancel').classList.add('hidden');f.entry_date.value=new Date().toISOString().slice(0,10);}
async function deleteGiving(id){if(!confirm('Delete this giving record?'))return;const r=await fetch(FAPI+'/finance/entries/'+id,{method:'DELETE'});const j=await r.json();alert(j.message||'Done');if(j.success)loadGiving();}
document.getElementById('giving-cancel').onclick=resetGiving;document.getElementById('giving-form').entry_date.value=new Date().toISOString().slice(0,10);document.getElementById('giving-form').addEventListener('submit',async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const id=document.getElementById('giving-id').value;const r=await fetch(FAPI+'/finance/entries'+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();document.getElementById('giving-feedback').textContent=j.message||'';if(j.success){resetGiving();loadGiving();}});Promise.all([loadCats(),loadGiving()]).then(()=>{if(new URLSearchParams(location.search).get('action')==='create')document.getElementById('giving-form').scrollIntoView({behavior:'smooth'})});
</script>
